# APPLICATION
spring:
  application:
    name: Connect Things
    description: Projeto desenvolvido pelo aluno Caio Benicio da Faculdade UNA de Uberl√¢ndia.
    version: project.version
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSSZ


# SERVER WEB //MQTT
server:  
  servlet:
    context-path: /
  port: 8081
    
# SERVER MQTT   
#broker:
# mqtt: tcp://127.0.0.1:1883
# user: caiosilva
# password: 506070
